# Generated by Django 3.2.13 on 2023-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAlignmentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1)),
                ('importance', models.IntegerField()),
                ('how_to_learn', models.CharField(choices=[('A', 'Autodidata'), ('T', 'Trabalho'), ('F', 'Faculdade')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('ranking_80000_hours', models.IntegerField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
